version: "3.8"
services:
  django_app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKED=redis://redis:6379/0
    depends_on:
      - db
      - redis 
  
  celery:
    build: .
    command: celery  -A core worker -l INFO
    volumes:
      - .:/app
    container_name: celery_container
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKED=redis://redis:6379/0    
    depends_on:
      - django_app
      - redis 

  redis:
    image: redis:alpine
    container_name: redis_container

  db:
    # image: postgres
    # volumes:

    #   - ./data/db:/var/lib/postgresql/data
    # environment:
    #   - POSTGRES_DB=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    # container_name: postgres_db

    image: mysql:5.7 # use an older version because the newest version contains some issues
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: 'django-app-db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - mysqldata:/var/lib/mysql
 

volumes:
  mysqldata:




